### ISSUE TITLE
anchors in storyblok pages in landing page don't always work

### ISSUE THREAD

**Issue by zguillen** [MSD-LIVE/issues#288]
See links from main dataset notebook page like this one: 

<img width="532" height="65" alt="Image" src="https://github.com/user-attachments/assets/594f9a5f-765b-4196-a414-16941cd05062" />
That goes to here:
https://dev.msdlive.org/help/resources/quick-guides/using-dataset-notebooks#scratch-about

But when clicking that link the page doesn't scroll all the way down to the scratch-about section.

**Comment by RebekahMarsPNNL** [comment]
Fixed :)

**Comment by zguillen** [comment]
I'm still seeing this happen but Carina is not. We noted that it works in Chrome (Carina's browser) but not MS Edge (my browser). Something in landing page app's js lib to scroll to anchor doesn't work well in edge.

**Comment by RebekahMarsPNNL** [comment]
Fixed in hotfix to landing page :)
